NVDA Example
GSA/open-product-accessibility-template pull request #160
Opened 2021-08-30 20:55 UTC by mgifford

Along with an error, I can't work through.

```
$ npx ts-node src/opat.ts validate -f opat/NVDA-2018.yaml -c catalog/2.4-edition-wcag-2.0-508-en.yaml
Invalid: catalog file is not in YAML format
```

2021-08-30 21:03 UTC, dmundra commented on opat/NVDA-2018.yaml
> +    notes: "GovReady-Q is a web application and an authoring tool. As such the Software & Authoring Tool Notes are all included within the Web for the 'Conformance Level' and 'Remarks and Explanation
@mgifford this note says 'GovReady'.

2021-08-30 21:04 UTC, dmundra commented on opat/NVDA-2018.yaml
> +    notes: "GovReady-Q is a web application and an authoring tool. As such the Software & Authoring Tool Notes are all included within the Web for the 'Conformance Level' and 'Remarks and Explanation
Looks like I missed that but it appears in Moodle and Plone as well.

2021-08-30 21:09 UTC, dmundra commented on opat/NVDA-2018.yaml
> +          - name: "web"
@mgifford duplicate `name: "web"` here.

2021-08-30 21:12 UTC, dmundra requested changes
Found the issue and commented on it.

Next one you will run into is:
> Invalid: criteria '504.2' is not included in 'Chapter 5: Software', criteria '504.2.3' is not included in 'Chapter 5: Software', criteria '504.2.4' is not included in 'Chapter 5: Software', criteria '602.3' is not included in 'Chapter 6: Support Documentation and Services'

2021-08-30 21:23 UTC, dmundra commented on opat/NVDA-2018.yaml
> +              notes: "In NVDA itself, there are no “breadcrumb trails” to follow."
@mgifford quotes in quotes I think are causing the pre-commit failures. If you switch this to regular quotes and escape them it should be fine.

2021-08-30 21:33 UTC, mgifford commented
I think I have all of these changes now

2021-08-30 21:43 UTC, dmundra commented
> I think I have all of these changes now

I get this validation error. Did I miss these in the catalog?

```
> npx ts-node src/opat.ts validate -f opat/NVDA-2018.yaml -c catalog/2.4-edition-wcag-2.0-508-en.yaml
Invalid: criteria '504.2' is not included in 'Chapter 5: Software', criteria '504.2.3' is not included in 'Chapter 5: Software', criteria '504.2.4' is not included in 'Chapter 5: Software', criteria '602.3' is not included in 'Chapter 6: Support Documentation and Services'
```

2021-08-30 21:51 UTC, dmundra commented
@mgifford I pushed up a fix to the catalog and the NVDA YAML. It is validating now. Do you want to generate the HTML and Markdown?

2021-08-30 22:13 UTC, dmundra commented
@mgifford added a fix to the error you were getting earlier. I am done with my changes so back to you.

2021-08-30 23:48 UTC, mgifford commented
Ok, .html & .markdown are there. Let me know what you think @dmundra

2021-08-31 13:35 UTC, dmundra approved these changes
Looking good. Thank you!

2021-08-31 13:35 UTC, merged